name: Get-ARM64-Docker-Images-Release

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称，多个用英文逗号分开'
        required: true
        default: 'alpine:latest,alpine/curl,busybox:stable-glibc'

jobs:
  pull_and_package:
    runs-on: ubuntu-22.04

    steps:
      # 步骤 1: 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤 2: 拉取 Docker 镜像并打包为 .tar.gz 文件
      - name: Pull Docker Images and Package
        run: |
          # 读取输入的 docker 镜像名称
          images="${{ github.event.inputs.docker_images }}"
          IFS=',' read -r -a image_array <<< "$images"

          # 循环处理每个镜像
          for image in "${image_array[@]}"; do
            echo "Pulling image: ${image} for ARM64"
            docker pull "${image}" --platform "linux/arm64"
            
            if [ $? -ne 0 ]; then
              echo "Error pulling image: ${image}"
              exit 1
            fi

            # 格式化镜像名，替换 '/' 为 '_' 和 ':' 为 '_'
            image_name="${image//\//_}"
            image_name="${image_name//:/_}"

            # 保存镜像为 tar 文件
            docker save "${image}" -o "${image_name}-arm64.tar"
            
            # 将 tar 文件压缩为 tar.gz
            gzip -c "${image_name}-arm64.tar" > "${image_name}-arm64.tar.gz"

            # 删除临时 tar 文件
            rm "${image_name}-arm64.tar"
          done

      # 步骤 3: 输出调试信息，列出所有生成的 tar.gz 文件
      - name: List generated files (debug step)
        run: |
          echo "Preparing docker images list (.tar.gz) files:"
          find $GITHUB_WORKSPACE -name "*.tar.gz"

          # 创建发布的时间戳
          release_name=$(TZ="Asia/Shanghai" date +'%Y-%m-%d %H:%M Build')
          echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV

      # 步骤 4: 创建 GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: DockerTarBuilder-ARM64
          name: ${{ env.RELEASE_NAME }} for ARM64
          body: |
            [![Github](https://img.shields.io/badge/RELEASE:DockerTarBuilder-123456?logo=github&logoColor=fff&labelColor=green&style=for-the-badge)](https://www.bilibili.com/video/BV1EZ421M7mL) [![Github](https://img.shields.io/badge/国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge)](https://wkdaily.cpolar.top/archives/1)
            ### How to use? For example
            `docker load -i alpine_latest.tar.gz `
            ### Video teaching
            [![Bilibili](https://img.shields.io/badge/Bilibili-123456?logo=bilibili&logoColor=fff&labelColor=fb7299)](https://www.bilibili.com/video/BV1yyq6YREdF)
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 步骤 5: 上传 Docker 镜像作为 Release 资源
      - name: Upload Docker images as release assets
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: DockerTarBuilder-ARM64
          files: ${{ github.workspace }}/*.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
